// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: darwin_service.proto

package darwin_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DarwinService_Update_FullMethodName          = "/proto.DarwinService/Update"
	DarwinService_ReportInGame_FullMethodName    = "/proto.DarwinService/ReportInGame"
	DarwinService_CreateCharacter_FullMethodName = "/proto.DarwinService/CreateCharacter"
	DarwinService_Ping_FullMethodName            = "/proto.DarwinService/Ping"
)

// DarwinServiceClient is the client API for DarwinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DarwinServiceClient interface {
	// Update the position of object in the world to the clients.
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (DarwinService_UpdateClient, error)
	// Client report the change of position and speed of a player.
	ReportInGame(ctx context.Context, in *ReportInGameRequest, opts ...grpc.CallOption) (*ReportInGameResponse, error)
	// Create a new character.
	CreateCharacter(ctx context.Context, in *CreateCharacterRequest, opts ...grpc.CallOption) (*CreateCharacterResponse, error)
	// Ping the server.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type darwinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDarwinServiceClient(cc grpc.ClientConnInterface) DarwinServiceClient {
	return &darwinServiceClient{cc}
}

func (c *darwinServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (DarwinService_UpdateClient, error) {
	stream, err := c.cc.NewStream(ctx, &DarwinService_ServiceDesc.Streams[0], DarwinService_Update_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &darwinServiceUpdateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DarwinService_UpdateClient interface {
	Recv() (*UpdateResponse, error)
	grpc.ClientStream
}

type darwinServiceUpdateClient struct {
	grpc.ClientStream
}

func (x *darwinServiceUpdateClient) Recv() (*UpdateResponse, error) {
	m := new(UpdateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *darwinServiceClient) ReportInGame(ctx context.Context, in *ReportInGameRequest, opts ...grpc.CallOption) (*ReportInGameResponse, error) {
	out := new(ReportInGameResponse)
	err := c.cc.Invoke(ctx, DarwinService_ReportInGame_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darwinServiceClient) CreateCharacter(ctx context.Context, in *CreateCharacterRequest, opts ...grpc.CallOption) (*CreateCharacterResponse, error) {
	out := new(CreateCharacterResponse)
	err := c.cc.Invoke(ctx, DarwinService_CreateCharacter_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darwinServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, DarwinService_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DarwinServiceServer is the server API for DarwinService service.
// All implementations must embed UnimplementedDarwinServiceServer
// for forward compatibility
type DarwinServiceServer interface {
	// Update the position of object in the world to the clients.
	Update(*UpdateRequest, DarwinService_UpdateServer) error
	// Client report the change of position and speed of a player.
	ReportInGame(context.Context, *ReportInGameRequest) (*ReportInGameResponse, error)
	// Create a new character.
	CreateCharacter(context.Context, *CreateCharacterRequest) (*CreateCharacterResponse, error)
	// Ping the server.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedDarwinServiceServer()
}

// UnimplementedDarwinServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDarwinServiceServer struct {
}

func (UnimplementedDarwinServiceServer) Update(*UpdateRequest, DarwinService_UpdateServer) error {
	return status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedDarwinServiceServer) ReportInGame(context.Context, *ReportInGameRequest) (*ReportInGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportInGame not implemented")
}
func (UnimplementedDarwinServiceServer) CreateCharacter(context.Context, *CreateCharacterRequest) (*CreateCharacterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCharacter not implemented")
}
func (UnimplementedDarwinServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDarwinServiceServer) mustEmbedUnimplementedDarwinServiceServer() {}

// UnsafeDarwinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DarwinServiceServer will
// result in compilation errors.
type UnsafeDarwinServiceServer interface {
	mustEmbedUnimplementedDarwinServiceServer()
}

func RegisterDarwinServiceServer(s grpc.ServiceRegistrar, srv DarwinServiceServer) {
	s.RegisterService(&DarwinService_ServiceDesc, srv)
}

func _DarwinService_Update_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UpdateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DarwinServiceServer).Update(m, &darwinServiceUpdateServer{stream})
}

type DarwinService_UpdateServer interface {
	Send(*UpdateResponse) error
	grpc.ServerStream
}

type darwinServiceUpdateServer struct {
	grpc.ServerStream
}

func (x *darwinServiceUpdateServer) Send(m *UpdateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DarwinService_ReportInGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportInGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarwinServiceServer).ReportInGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DarwinService_ReportInGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarwinServiceServer).ReportInGame(ctx, req.(*ReportInGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DarwinService_CreateCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarwinServiceServer).CreateCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DarwinService_CreateCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarwinServiceServer).CreateCharacter(ctx, req.(*CreateCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DarwinService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarwinServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DarwinService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarwinServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DarwinService_ServiceDesc is the grpc.ServiceDesc for DarwinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DarwinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DarwinService",
	HandlerType: (*DarwinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportInGame",
			Handler:    _DarwinService_ReportInGame_Handler,
		},
		{
			MethodName: "CreateCharacter",
			Handler:    _DarwinService_CreateCharacter_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _DarwinService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Update",
			Handler:       _DarwinService_Update_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "darwin_service.proto",
}
